// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List leads from the CRM, optionally filtered by stage and/or a text search across name, company, phone.",
  inputSchema: {
    stage: z.enum(["new", "qualified", "unqualified", "contacted", "meeting", "won", "lost"]).optional().describe("Filter by pipeline stage."),
    search: z.string().optional().describe("Case-insensitive substring match on full_name, company_name or phone."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db(ctx).from("leads").select("id, full_name, company_name, phone, email, stage, source, platform, campaign_name, created_at, callback_date, offer_id").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("stage", stage);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`full_name.ilike.${s},company_name.ilike.${s},phone.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { leads: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead",
  description: "Fetch one lead by id, including its contact logs.",
  inputSchema: { id: z2.string().uuid().describe("Lead UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = db2(ctx);
    const { data: lead, error } = await client.from("leads").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!lead) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    const { data: logs } = await client.from("contact_logs").select("*").eq("lead_id", id).order("date", { ascending: false });
    const payload = { lead, contact_logs: logs ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/update-lead-stage.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_stage_default = defineTool3({
  name: "update_lead_stage",
  title: "Update lead stage",
  description: "Change the pipeline stage of a lead.",
  inputSchema: {
    id: z3.string().uuid(),
    stage: z3.enum(["new", "qualified", "unqualified", "contacted", "meeting", "won", "lost"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, stage }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db3(ctx).from("leads").update({ stage }).eq("id", id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { lead: data } };
  }
});

// src/lib/mcp/tools/add-contact-log.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_contact_log_default = defineTool4({
  name: "add_contact_log",
  title: "Add contact log",
  description: "Log a contact attempt (call, email, message) for a lead.",
  inputSchema: {
    lead_id: z4.string().uuid(),
    type: z4.string().describe("e.g. call, email, whatsapp"),
    reached_customer: z4.boolean().optional(),
    comment: z4.string().optional(),
    date: z4.string().datetime().optional().describe("ISO timestamp; defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db4(ctx).from("contact_logs").insert({
      lead_id: input.lead_id,
      type: input.type,
      reached_customer: input.reached_customer ?? null,
      comment: input.comment ?? null,
      ...input.date ? { date: input.date } : {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { log: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wlalcftxyqozrmzcywus";
var mcp_default = defineMcp({
  name: "epower-crm-mcp",
  title: "epower CRM",
  version: "0.1.0",
  instructions: "Tools for the epower CRM: list and inspect leads, update pipeline stages, and log contact attempts. All calls run as the signed-in CRM user and respect RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, update_lead_stage_default, add_contact_log_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
